### ISSUE TITLE
gamebreaking crash at settlement sheet

### ISSUE THREAD

**Issue by Ezekiel2703** [toconnell/kdm-manager#202]
Hi, 

When accessing the setllement sheet an internal server error is reported (see bottom of this message). There is no way to access the setllement sheet now even after restarting, logging out, etc. This error occured when I tried to add a dragon iron resource. Hope this can be resolved in order for us to continue playing.

Thanks in advance!

The following is reported:

Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 34, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 658, in current_view_html
 output += self.render_user_asset_sheet("settlements")
File "/home/toconnell/kdm-manager/v1/session.py", line 558, in render_user_asset_sheet
 output = S.render_html_form()
File "/home/toconnell/kdm-manager/v1/assets.py", line 6193, in render_html_form
 storage = self.get_storage("html_buttons"),
File "/home/toconnell/kdm-manager/v1/assets.py", line 4197, in get_storage
 resource_pool[resource_key] += 1
KeyError: 'iron'

**Comment by toconnell** [comment]
Hello!

My name is Tim and I maintain the Manager.

I see your issue and it's a simple one for me to fix. I am currently
working on putting a new release into Production, so I will push a quick
change out in the next 15 minutes or so that should fix you up.

Sorry about that! I'll shoot you a quick email when it looks fixed

Thanks for reporting the issue. And thanks for using the Manager!

TOC

I'll shoot you a quick

**Comment by toconnell** [comment]
OK, this is a problem caused by a bad key under resource type. I just monkey-patched it out for now in Production and it'll be included in the Anniversary Release when that rolls.

**Comment by toconnell** [comment]
```
diff --git a/v1/game_assets.py b/v1/game_assets.py
index 59ca1fa..eed0579 100644
--- a/v1/game_assets.py
+++ b/v1/game_assets.py
@@ -1770,7 +1770,7 @@ items = {
     "Dragon Iron": {
         "expansion": "Dragon King",
         "location": "Dragon King Resources",
-        "resource_family": ["scrap","iron"],
+        "resource_family": ["scrap"],
     },
     "King's Tongue": {
         "expansion": "Dragon King",
```
