### ISSUE TITLE
Delete Settlement generates 500 Server Error

### ISSUE THREAD

**Issue by gregrebholz** [toconnell/kdm-manager#210]
Enabled 'settlement deletion' in settings and tried to delete a "Testing" settlement (the first and only on my account).  Resulted in the following error, session was lost and required logging in again, and the settlement still exists --

500 - Server Explosion!

The server erupts in a shower of gore, killing your request instantly. All other servers are so disturbed that they lose 1 survival.

Caught exception while processing parameters for email@gmail.com (5876f48b8740d96f97115049)!

FieldStorage(None, None, [MiniFieldStorage('remove_settlement', '5876f5388740d97007a5cc5c')])

Please report errors and issues at https://github.com/toconnell/kdm-manager/issues

Use the information below to report this error:

2017-01-12 03:29:16.998221

Traceback:

Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 61, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 466, in process_params
 S = assets.Settlement(settlement_id=s_id, session_object=self)
File "/home/toconnell/kdm-manager/v1/assets.py", line 3183, in __init__
 self.set_settlement(settlement_id, update_mins)
File "/home/toconnell/kdm-manager/v1/assets.py", line 3206, in set_settlement
 self.update_mins()
File "/home/toconnell/kdm-manager/v1/assets.py", line 3239, in update_mins
 self.update_timeline_with_story_events()
File "/home/toconnell/kdm-manager/v1/assets.py", line 3681, in update_timeline_with_story_events
 event = self.get_event(m_dict["story_event"])
File "/home/toconnell/kdm-manager/v1/assets.py", line 3520, in get_event
 all_events = self.get_api_asset("game_assets","events")
File "/home/toconnell/kdm-manager/v1/assets.py", line 3296, in get_api_asset
 raise AttributeError(msg)
AttributeError: [email@gmail.com (5876f48b8740d96f97115049)] failed to initialize API asset for 'Testing' (5876f5388740d97007a5cc5c)

**Comment by toconnell** [comment]
Looks like we actually initialize a settlement object from assets.py before we delete it. Here's the pertinent code from session.py:

```
472         if "remove_settlement" in self.params:
473             self.change_current_view("dashboard")
474             s_id = ObjectId(self.params["remove_settlement"].value)
475             S = assets.Settlement(settlement_id=s_id, session_object=self)
476             user_action = "removed settlement %s" % S
477             S.remove()
```

Obviously we need an API asset to initialize the settlement object, but in terms of session.py, we haven't actually retrieved one yet, because we haven't set the current_session attrib.

Which is to say that we're probably going to either a.) have to skip the initialization of the object somehow or b.) grab an API asset outside of normal workflow.

Gotta reflect on that for a while.

**Comment by toconnell** [comment]
Removing survivors is broken as well.

**Comment by toconnell** [comment]
This is fixed for settlements. I think the idea is going to be to have the session set the current settlement, just like we would if we were modifying an asset, initialize the settlement normally and then call its remove() method:

```
472         if "remove_settlement" in self.params:
473             s_id = ObjectId(self.params["remove_settlement"].value)
474             self.set_current_settlement(s_id)
475             S = assets.Settlement(settlement_id=s_id, session_object=self)
476             S.remove()
477             user_action = "removed settlement %s" % S
478             self.change_current_view("dashboard")
```

**Comment by toconnell** [comment]
Survivor removal is fixed:

```
480         if "remove_survivor" in self.params:
481             # we actually have to get the survivor from the MDB to set the
482             # current settlement before we can initialize the survivor and
483             # use its remove() method.
484             s_id = ObjectId(self.params["remove_survivor"].value)
485             s_doc = mdb.survivors.find_one({"_id": s_id})
486             self.set_current_settlement(s_doc["settlement"])
487             S = assets.Survivor(survivor_id=s_id, session_object=self)
488             S.remove()
489             user_action = "removed survivor %s from %s" % (S, S.Settlement)
490             self.change_current_view("view_campaign", asset_id=S.survivor["settlement"])
```

Closing this out.
