### ISSUE TITLE
Remove A&I drop-down is not working

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#226]
From email:

> When trying to remove an ability or impairment from a survivor it can be selected from the dropdown box, but the page will not save and the abilities and impairments stay on the character sheet.

Looks like the form in the legacy app is missing a submit.

**Comment by toconnell** [comment]
Turns out that this is missing an ng-change/on-change:

```
    <select
        class="$select_class"
        name="remove_ability"
        ng_model="$ng_model"
        ng_change="$ng_change"
        onchange="$on_change"
    >
      <option selected disabled hidden value="">Remove Ability or Impairment</option>
    <option>Crystal Skin</option></select>
```

**Comment by toconnell** [comment]
Fixed:

```
    <select
        class="$select_class"
        name="remove_ability"
        ng_model="$ng_model"
        ng_change="$ng_change"
        onchange="this.form.submit()"
    >
      <option selected disabled hidden value="">Remove Ability or Impairment</option>
    <option>Leprosy</option></select>
```

This is fixed and going out in the next prod release.

**Comment by WayForger** [comment]
This has remains a pretty frustrating issue for me. 
![screen shot 2017-07-31 at 12 17 31 am](https://user-images.githubusercontent.com/30420007/28762592-cf65d1f6-7585-11e7-8271-870486289bd2.png)
