### ISSUE TITLE
Hello. I have a display problem, help plz.

### ISSUE THREAD

**Issue by nabuko81** [toconnell/kdm-manager#231]
Hi everyone,

It's my first time here and my first issue.
First I want to thank every person who create this marvelous kdm-manager.

So here is my problem, when I use kdm-manager on an Ipad it is display HUGE style, too HUGE to be use. I test on 2 different Ipad with Safari Firefox and chrome and it s the same problem. I can't manage to resize it i try with the preference of the browsers or the Ipad, and it's still **ENORMOUS**.

But when I use kdm-manager on Android, and different web browser, there are no problems a at all.

Plz help me, some of my fellow players only have Ipad and can't properly use kdm-manager ;(

Hope to read you soon ;) Bye

**Comment by toconnell** [comment]
Greetings!

Thanks for using the Manager!

I apologize for the presentation issue: I've tried to spend time supporting
iPad users, but I admit that it hasn't been a very high priority and iPad
support for the Manager is not where it ought to be.

Can you help me understand your issue a little bit better?

When I emulate an iPad in my development environment, the settlement
summary looks like this:


​
Does it it look much different for you? Are the font-sizes larger than
these? Or are there other elements of the presentation that seem huge?

Thanks!
TOC

**Comment by nabuko81** [comment]
I cant see the picture in your post.

But to be more specific, kdm open directly in zoom mode, and you can't dezoom, but on android no problem at all. I'll ask to my friends with ipads to send me pictures of the problem so you can better understand. We want to play with kdm-manager because its so cool ^_^

**Comment by toconnell** [comment]
Awesome! When you get them, attach them here (or, if you can't just email them to me directly: toconnell@tyrannybelle.com).

Thanks again for taking the time to write in!

**Comment by toconnell** [comment]
Hey @nabuko81: I am thinking about closing this issue out. Did you ever get a chance to get those screen captures?
