### ISSUE TITLE
Sunstalker Resources Issue

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#238]
From email:

```
 [57b79eed421aa927c4899433] has submitted an error report!

The report goes as follows:
Sunstalker resources unable to add to storage. No option to add poping up, even record successful hunt, added expansion, and it shows sky reef location items to add
```

**Comment by toconnell** [comment]
Caleb confirms this in chats:
```
toconnell [8:27 AM] 
also, @channel, my stuff is all packed (or else I'd look this up on my own), but the Sunstalker does not have a resource deck, correct? All of the weird fiddly bits of the Sunstalker are strange resources, are they not?

caleb [8:28 AM] 
It's got it's own resource deck
That's lion god
```

**Comment by toconnell** [comment]
Confirmed: these definitely got removed from the legacy _game_assets.py_ at some point. 

Screen cap:

![sunstalker_resources](https://user-images.githubusercontent.com/48043/27550420-29034162-5a65-11e7-82a2-18e873a3b9bf.png)

**Comment by yaseiko** [comment]
The Sunstalker has both strange resources and a normal resource deck. If needed can list all sunstalker specific resources and what they are if needed.

**Comment by toconnell** [comment]
@yaseiko They actually were included at one point, but somehow got removed (I blame myself: it was probably a bad merge or something). 

Unfortunately, I'm not going to get them re-added for the release that's happening today, but I plan to look at getting them back in for the next release after that (which will come later this week or early this weekend).

At any rate, if it ends up being the case that I can't find them, I might actually ask you to type them out because I am in the middle of moving and all of my KD stuff is in storage.

Thanks for checking in! I'll keep you posted.

**Comment by toconnell** [comment]
This is getting fixed in the next release.
