### ISSUE TITLE
Update webserver to use SSL; reroute HTTP requests to HTTPs

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#242]
I got shamed on Reddit this afternoon:

![reddit_shame_ssl](https://user-images.githubusercontent.com/48043/27701007-1f81b652-5cc5-11e7-8371-dae5d07ade41.PNG)

Items:
- [x] get a cert
- [x] update legacy webapp javascript
- [x] update legacy api.route_to_dict() and other legacy requests methods
- [x] update legacy webapp nginx config
- [x] update API nginx config

**Comment by eugene-shuvaev** [comment]
Just bumping the issue because https://thewatcher.io/ is what should it be :)

**Comment by toconnell** [comment]
Doing this on certbot: https://certbot.eff.org/#ubuntuxenial-nginx

**Comment by toconnell** [comment]
Just did this on the scratch domain and it looks like everything is A-OK: https://thelaborinvain.com/

**Comment by toconnell** [comment]
@eugene-shuvaev The next release of the Manager is going to support optional HTTPS  (you can do it now, but nothing will work due to hard-coded HTTP stuff). Once that burns in overnight, I'm going to pull the trigger on mandatory HTTPS.

**Comment by toconnell** [comment]
Just rolled this. God help us.
