### ISSUE TITLE
Innovation deck contains innovations from expansions I didn't enable

### ISSUE THREAD

**Issue by eugene-shuvaev** [toconnell/kdm-manager#244]
Hello,

my settlement's innovation deck contains Bloodline and Settlement Watch innovations, which belong to Dragon King and Manhunter expansions, if I'm not mistaken. But I don't have this expansions and have never enabled them in the Expansion Content section.

It's not a huge problem, but is a bit annoying when you need to form your innovation deck and check if everything is there.

**Comment by toconnell** [comment]
@eugene-shuvaev I'm checking it out now. If I can figure it out and fix it this morning, I will include the fix in today's release. 

More soon!

**Comment by toconnell** [comment]
Confirmed and reproduced:
![i_deck_exp_bug](https://user-images.githubusercontent.com/48043/27736357-73aced6a-5d69-11e7-837d-c98784263711.PNG)

**Comment by toconnell** [comment]
Got it. This was a problem in _models.settlements.Settlement.get_innovation_deck()_ where we processed innovation consequences but did not check to see if consequences were compatible.

Git diff:
```
@@ -883,12 +883,13 @@ class Settlement(Models.UserAsset):

         # now, we use the baseline and the consequences list to build a deck
         deck_dict = {}
-
         for c in consequences:
             if c not in self.settlement["innovations"]:
                 if c in available.keys():
                     del available[c]
-                deck_dict[c] = I.get_asset(c)
+                asset_dict = I.get_asset(c)
+                if self.is_compatible(asset_dict):
+                    deck_dict[c] = asset_dict
```

This one will go out in today's release.

**Comment by toconnell** [comment]
@eugene-shuvaev Thanks for writing in with this one! The patch/fix is going out with this morning's build.
