### ISSUE TITLE
Available Endeavors list isn't correct

### ISSUE THREAD

**Issue by eugene-shuvaev** [toconnell/kdm-manager#246]
Hello Timothy,

I have an issue with the Available Endeavors list on my settlement's campaign summary:
1. I have "Build Organ Grinder", "Build Skinnery" and "Build Bone Smith" as available actions, but I've already built all of them. 
2. Then it shows "Build Leather Worker", "Build Stone Circle" and "Build Weapon Crafter" actions, which isn't totally correct because I've built Leather Worker.
3. The list doesn't contain "Leather Making", which should be there, because I have also innovated Ammonia.

The list also doesn't show any endeavor activities from the Innovations, but I'm almost sure it never did :)

----

- [x] bogus available actions (false-positive) due to prereq evaulation failure
- [x] Leather-making missing

**Comment by toconnell** [comment]
@eugene-shuvaev I'm checking this out now. 

As part of the work on http://thewatcher.io, we're moving a lot of legacy webapp functionality to the API in the last few releases, and it's breaking a few things: I have a pretty good idea of what might be causing this, however and I think I can fix it in the next release.

More soon.

**Comment by toconnell** [comment]
Confirmed: the legacy webapp's _assets.Settlement.get_endeavors()_ method was trying to pull key information using handles, rather than names (the legacy app has no support for handles).

I just updated the method to get names:

```
4101         innovation_names_list = copy(self.get_game_asset("innovations", update_mins=False, handles_to_names=True     ))
4102         location_names_list = copy(self.get_game_asset("locations", update_mins=False, handles_to_names=True))
4103
4104         # this is a list of locations and innovations together that will be used
4105         #  later to determine if the settlement meets the requirements for an
4106         #  endeavor
4107         prereq_assets = innovation_names_list
4108         prereq_assets.extend(location_names_list)
```

That appears to fix the issue of the already-built innovations/locations not going away.

Now to check out the other thing.

**Comment by toconnell** [comment]
Innovations had a similar problem and they're fixed now.

**Comment by toconnell** [comment]
@eugene-shuvaev Thanks for reporting this one!

I just fixed it and the correction will go out in the next release, which will be either later today or possibly tomorrow, depending on how much progress I make in the next hour (haha).

Thanks again and keep 'em coming!
