### ISSUE TITLE
Green Savior dream name is incorrect

### ISSUE THREAD

**Issue by eugene-shuvaev** [toconnell/kdm-manager#250]
Hello Timothy,

a minor one: on savior color selector it says "Dream of the Throne" instead of "Dream of the Crown".

![image](https://user-images.githubusercontent.com/21055254/27861926-90df10d6-618b-11e7-941f-927768a7b205.png)

**Comment by toconnell** [comment]
![doc_snip](https://user-images.githubusercontent.com/48043/27867080-4328fabe-615e-11e7-97f6-b2d71bb4eb3b.PNG)

@eugene-shuvaev I'm going to move the Savior controls from the legacy webapp to the API in the next release (continuing work on issue #99) and I'll fix this when I do.

Thanks for checking in with this one!

Also, not sure if you follow the dev blog, but I added you to [the acknowledgements](http://kdm-manager.blogspot.com/p/credits-and-acknowledgements.html). Thanks again for reporting issues!

**Comment by toconnell** [comment]
I just updated this; it will be fixed in the next release.

```
toconnell@mona:~/kdm-manager/v1$ git diff html.py
diff --git a/v1/html.py b/v1/html.py
index 0965fb8..c504e4a 100644
--- a/v1/html.py
+++ b/v1/html.py
@@ -2031,7 +2033,7 @@ class survivor:
                 <input type="hidden" name="modify" value="survivor">
                 <input type="hidden" name="asset_id" value="$survivor_id">
                 <input type="hidden" name="set_savior_type" value="green">
-                <button class="affinity_green">Dream of the Throne</button>
+                <button class="affinity_green">Dream of the Crown</button>
             </form>

             <form method="post" action="/">
```

**Comment by eugene-shuvaev** [comment]
@toconnell not only I follow the blog, I've already started bragging to my friends about being a QA :)

Thanks a lot for both the manager and the acknowledge. I'm really looking forward for The Watcher.
