### ISSUE TITLE
Controls of Death throw JS/API error

### ISSUE THREAD

**Issue by WayForger** [toconnell/kdm-manager#262]
The "An error occurred" message appears upon choosing a cause of death. The error message occurs regardless of chosen option and the survivor is not moved to the "The Dead" section. 
![screen shot 2017-07-24 at 5 13 24 pm](https://user-images.githubusercontent.com/30420007/28545065-85124018-7093-11e7-8d6b-d1e39529499a.png)

**Comment by toconnell** [comment]
I can't presently replicate this is OSX/Android Chrome 59, but I'll check it out on Windows as soon as I get a Windows machine up and running and work on it for the next release.

@WayForger

**Comment by toconnell** [comment]
From email:

```
Strange, I just tried again and now I can kill the survivors I was unable to 2 days ago, and then I tried to reload the page, log out and log in again, and tried refreshing cache and nothing worked.

The problem with the abilities is that I added by mistake some abilities that the survivor don´t have. When I hover the cursor over the ability description in the carácter page a text box tells me that clicking or taping it should remove it, but it doesn’t work. I click over the ability but nothing happens.
```

**Comment by WayForger** [comment]
@toconnell, I am currently running the Manager on OSX Sierra Chrome v59. While the character's "Dead" box is marked, they never transition from the pool of living survivors and join the dead. It shows that this survivor died of Necrotoxic Mistletoe but, upon reloading the Campaign summary, she never leaves the living. 

![screen shot 2017-08-06 at 12 52 09 am](https://user-images.githubusercontent.com/30420007/29000714-21223afa-7a42-11e7-8092-27bdb501ed37.png)

I also think it would be a nice touch if you were able to include the cause of death next to the lantern year in which the survivor passed.

**Comment by WayForger** [comment]
I still have this same error happening. I'm pretty sure the error is just in the movement of the deceased to The Dead.

**Comment by toconnell** [comment]
@WayForger Hey--I'm looking at this right now and I have a quick question.

If you mark the survivor dead, go back to the campaign summary view and then go back to the survivor sheet and click on the "Dead" box, does the previously-entered cause of death still show up in the pick list?

Or is it just like you never touched it at all?

**Comment by WayForger** [comment]
Like I never touched the controls of death at all. It says they've "died" in the log but no movement occurs. It seems to only happen with survivors that have been around for awhile, as the death of newly created survivors don't throw the error.

**Comment by toconnell** [comment]
@WayForger I'm finishing up a new release of the Manager that should address this and a few other Javascript order-of-operation/race-condition issues that cause various UI/UX failures. I'm going to try to get everything ready to go tonight, do some QA on it when I've got fresh eyes in the morning and have it ready to go early tomorrow.

Let's leave this one open, however, just in case it continues to be a problem after the release.

**Comment by toconnell** [comment]
Hey @WayForger , I've heard from a couple of other guys that this issue appears to have been resolved after last Saturday's release. Have you run into it since then at all?

**Comment by WayForger** [comment]
Haven't been able to use it at all due to personal affairs. I will check it out over this weekend and get back to you. Everything is looking great though.

**Comment by toconnell** [comment]
I'm closing this one out because a.) I am no longer able to replicate it in FireFox and b.) I haven't heard any complaints lately, which leads me to think that single sheet loads (which went out a few releases back) solved this (as I suspected it might).
