### ISSUE TITLE
JS: Click/tap to remove A&I is not working

### ISSUE THREAD

**Issue by WayForger** [toconnell/kdm-manager#266]
Accidentally added Ageless and Shattered Jaw and have been unable to fix this character's sheet. Another character now suffers several disorders similarly after trying to add an ability. I would very much appreciate this issue being examined—it's quite frustrating. 
![screen shot 2017-08-03 at 4 55 15 pm](https://user-images.githubusercontent.com/30420007/28943369-90c8d0da-786c-11e7-9c9e-fc59a0b00e54.png)

**Comment by toconnell** [comment]
I can replicate this in OSX/Chrome 59. 

(I can't really do any debugging right now, but it's definitely not working, even when all JS elements on the page appear to load correctly.)

I will collect other related issues under this one.

@WayForger FYI

**Comment by toconnell** [comment]
This is related to issue #226, which is resolved, so this broke after that.

**Comment by toconnell** [comment]
Found it. The code to remove somehow got...disappeared in a recent revision:

```
1899    ng-click="rmAI($index, ai_handle)"
```

Weirdly, it's present in d5ab8072cc1b56cb46e99fe3aeece3f473eddb8b, so I'm not sure where it went.

**Comment by toconnell** [comment]
Looks like it got zapped in af2a6f1b6c29dc2e30b3d63e20ad82b297becd95

**Comment by toconnell** [comment]
@WayForger This is resolved. I'll push the fix out in the next release.
