### ISSUE TITLE
Survivor Sheet: add "Once Per Lifetime" section with a dropdown

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#353]
This would be net-new on the sheet and in the API, so this ticket (for now) is just a stub to remind me to do it.

Items:

- [ ] Forbidden Dance (if Forbidden Dance innovation)
- [ ] Nominated for Partnership (if Partnership innovation)
- [ ] Scarification - Initiation (endeavor)
- [ ] Sacred Pool Purification Ceremony endeavor
- [x] Put the SotF toggle in this group

**Comment by KingofTown** [comment]
Survival of the Fittest should be included in this

**Comment by toconnell** [comment]
@KingofTown Hey--this actually already is a feature of the webapp: once you add the SotF principle, the checkbox should pop up on your Survivor Sheets.

To your point though, when I end up getting around to building this out as a feature, I will definitely reorganize the UI so that the SotF reroll is grouped with all of these things.

In the meantime, let me know if you run across anything else that belongs on this list!

**Comment by toconnell** [comment]
Feature work on the legacy webapp is no longer happening. Closing this. 

Opened it in AKDM Manager as a launch feature: https://github.com/theLaborInVain/Advanced-KDM-Manager/issues/4
