### ISSUE TITLE
No Internet Connection Error

### ISSUE THREAD

**Issue by Chaorain** [toconnell/kdm-manager#408]
Occasionally I found a bug while working on  KDM-manager.com. There is no error message, the screen displays "no internet connection" re-fleshing the site brings me back to the page I was just on.

I have only seen this error when trying to navigate to a new page that requires loading. I.e. Editing a survivor, the settlement sheet, the settlement summary and returning to the dashboard. Again refreshing brings me back to the page I was just looking at after a brief load. Tapping on the same link generally produces the same result, occasionally I've gotten around this problem by tapping a different link, I.e. selecting a departing survivor in the side bar instead of the summary sheet. Sometimes I've gotten around the problem by going to a different sheet, I.e. the dashboard, then navigating back to where I want to go. Sometimes I've been unable to access any other sheets, in this case I have to wait several minutes, 5-10 I think, before I'm able to access any other sheets. I've determined no pattern for these events. 

I've encountered this problem primarily on my cell phone but also on my iPad. My computer however was able to access the site normally. I tried Chrome and Safari on my iPhone with the same results. I only tried Chrome on my iPad and computer. Here are the model numbers and what not. 

Cell Phone:
iPhone 6s
iOS: 10.3.3
Chrome: 62.0.3202.70

iPad:
iPad Pro (2015)
iOS: 9.3.5
Chrome: 62.0.3202.70

Computer
Windows 10
Chrome: 61.0.3163.100

**Comment by toconnell** [comment]
This seems like it's going to be tricky to reproduce. As usual, I suspect a Javascript issue.

(Parenthetical: I really need to get an iPad to test this stuff)

**Comment by toconnell** [comment]
@Chaorain Thanks for documenting all of this. I will be mostly working on break/fix, security and enhancements required for the first release of The Watcher during this month, and I will do my best to reproduce and resolve this one!

**Comment by Chaorain** [comment]
I would be happy to test for you. I have not seen any way to be certain as to when the bug will happen but I could always play around the site for a couple hours a day to try and trigger it.

**Comment by Chaorain** [comment]
I just had this trigger while attempting to upload a picture for a survivor. John Galt in my Scar campaign.

**Comment by toconnell** [comment]
@Chaorain What was the file size of the picture? I'm thinking that the webserver might be timing out requests that try to move too much data...?

**Comment by Chaorain** [comment]
I'm unsure of the file size, I'm on my phone right now. I did crop the image and upload it first. Then I saw the proportions were off so I undid the crop and tried uploading again. That is when it failed. Here is the link to the image: https://upload.wikimedia.org/wikipedia/commons/c/c3/John_Galt_7.jpg

Also it appears that character images on the survivor sheets are being stretched instead of allowing for blank space.

**Comment by toconnell** [comment]
Hey @Chaorain: the last release of the Manager (that went out yesterday afternoon) redesigned/reimplemented/refactored the controls for updating survivor avatars. 

When you get a chance, can you let me know if you're still running into this issue?

Thanks!

**Comment by Chaorain** [comment]
Sorry for the delay, I just updated my campaign. I was able to upload 2 photos from my iPhone for two different survivors. However afterwards I was unable to return to the settlement overview due to the "no internet connection" error. 

I was able to update my campaign from my desktop computer without issue.

**Comment by toconnell** [comment]
Hey @Chaorain: thanks for checking back in!

Which iPhone are you using?

**Comment by Chaorain** [comment]
iPhone 6S. When I tested it I was on iOS 10.3.3 I think. My Chrome version is currently 63.0.3239.73, it may have updated since I tried it, not sure.
