### ISSUE TITLE
User: new() method not receiving password from login screen

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#423]
...due to a potential encoding issue?

From reddit:

> Hey, I'm using chrome 62.0.3202.94, windows 10, and when I tried to signup for a new user at https://kdm-manager.com I got the attached error. I replicated a couple of times; I did use a password manager (ChromeIPass linked to KeePass) to enter the password, and of course the password was a mish-mash of garbage; Is something breaking because of a character problem? I also tried disabling ghostery just in case, but still the same error.
> https://imgur.com/a/8NlEy

**Comment by realthecaffiend** [comment]
I messed around with trying to create another new user; I replicated the problem with the following generated password. My standard assumption when I can have it break on a password like this is indeed character encoding. I used a plaintext password and it worked fine, same email, so the only input varying is the password. 

Usually when I see this in a professional engagement I turn to something like sqlmap, but that's not polite if I am not asked; It does raise a concern that something is not being sanitized however and could be vulnerable to attacks. 

Happy to provide more info if just using this password doesn't replicate for some reason! 

[8@H+70n\4gALJi_e'~RQFczm3gGX]Cpgu5

**Comment by toconnell** [comment]
Weirdly, using this password is working in dev: `[8@H+70n\4gALJi_e'~RQFczm3gGX]Cpgu5`

This one might have to wait for next week for a resolution...

**Comment by toconnell** [comment]
Hey @realthecaffiend after you've registered, are you able to change/update your password to one of these randomized strings? 

Like, on the Dashboard, if you click on "System" and change your password, do these work for that? Or does it throw an error there as well?

**Comment by realthecaffiend** [comment]
Well that's neat; After updating the password worked, I went to create a new one. It also worked with that mess of characters. 

Was there an API change in between or something that fixed it by accident? That's the best and worst kind of fix

This currently seems fixed at least on the https site as of now when I tried it, 1620 mountain time

**Comment by toconnell** [comment]
@realthecaffiend I actually did do a small production code-push last night as part of the cut-over to mandatory SSL and it included a handful of small, break/fix type items: one of the things it touched on was the way that JSON is packaged up by the webapp for API requests, which might have had something to do with it.

I agree with what you're saying about the best and worst kind of fix though, because I would really like to know exactly what the problem was!

At any rate, thanks for all of the attention/time on this! I'm going to close this issue out for now, but feel free to re-open (or open a new one: whatever's easy) if you run into it again.

Thanks again!
