### ISSUE TITLE
Session not preserved

### ISSUE THREAD

**Issue by Chaorain** [toconnell/kdm-manager#425]
It seems my sessions are not preserved on KDM-manger.com despite the option being enabled. It seems to save the session for 6 hours-ish before requiring a new login.

I am only using one device so I do not believe that is the isssue. I've noticed that this happens even when I stay on the same network for the 6 hour period.

**Comment by toconnell** [comment]
I started working on this and realized that the legacy webapp _admin.prune_sessions()_ method was in real need of some TLC (i.e. looked like I was huffing bath salts when I wrote it).

Refactor:
```
toconnell@mona:~/kdm-manager/v1$ git diff admin.py
diff --git a/v1/admin.py b/v1/admin.py
index 5a0f31d..d077749 100755
--- a/v1/admin.py
+++ b/v1/admin.py
@@ -58,15 +58,22 @@ def prune_sessions():
     pruned_sessions = 0
     preserved_sessions = 0
     for s in old_sessions:
+
+        # set some user and session details
         user = mdb.users.find_one({"login": s["login"]})
-        U = assets.User(user["_id"], session_object=admin_session)
-        if U.is_admin():
+        preserve = user['preferences'].get('preserve_sessions', False)
+        session_age = datetime.now() - s['created_on']
+
+#        logger.debug("preserve_sessions: %s; session age: %s days" % (preserve, session_age.days))
+
+        # now preserve or prune
+        if user.get('admin', False):
             preserved_sessions += 1
-        elif U.user['preferences'].get("preserve_sessions",False) and s["created_on"] > thirty_days_ago:   # if it's older than 30 days, ignore the preference
+        elif preserve and session_age.days < 30:
             preserved_sessions += 1
         else:
             s_id = s["_id"]
-#            logger.debug("Pruning old session '%s' (%s)" % (s_id, s["login"]))
+#            logger.debug("Pruning old session '%s' (%s; age: %s)." % (s_id, s["login"], session_age.days))
             remove_session(s_id, "admin")
             pruned_sessions += 1
```

I think the old version had some problems with the generic `thirty_days_ago` reference, so I just shit-canned that completely. 

Also, fully initializing the user at that point was...just wasteful, so I 86'd that as well.

Now we just read the user, check the age of their session and then inflict our conditions.

Fix goes out in the next release.
