### ISSUE TITLE
Updating a survival via set_attributes doesn't create an event log record

### ISSUE THREAD

**Issue by CalebKester** [toconnell/kdm-manager#431]
Tried managing a survivors survival through the set_attributes action and it doesn't show up in the event log. I tested some of the other attributes and it successfully added on.

I tested both with the watcher and kdm manager and neither one of them added a log to the event_log call.

**Comment by toconnell** [comment]
@CalebKester I believe it: event logging was added after a lot of the initial development and I probably missed this. I'll check it out right now.

**Comment by toconnell** [comment]
@CalebKester I've been trying to replicate this, and I think it might actually be a problem with the _get_event_log_ route.

When I do this:
>https://192.168.0.110:8013/survivor/set_attribute/58f9feb18740d974fe669621
`{"attribute": "survival", "value": 2}`
I see this in the logs:
```
[2017-12-01 10:27:53] DEBUG:    Lady Kluck [F] (58f9feb18740d974fe669621) event: demo@kdm-manager.com set Lady Kluck [F] 'survival' to 2
[2017-12-01 10:27:53] INFO:     Saved Lady Kluck [F] (58f9feb18740d974fe669621) to mdb.survivors successfully!
[2017-12-01 10:27:53] DEBUG:    [POST] https://192.168.0.110:8013/survivor/set_attribute/58f9feb18740d974fe669621 response in 0:00:00.294361
```

So I'm...pretty sure it's logging. What I'd like to be able to rule out is whether 

Can I get you to paste your POST body from both the _set_attribute_ and the _get_event_log_  calls, so I can triangulate it?

**Comment by CalebKester** [comment]
Survival (doesn't log)
`https://api.thewatcher.io/survivor/set_survival/57ccc3018740d951a50eb448`
`{"user_id":"57b9e779421aa903403a7432","value":1}`

Bleed (logs correctly)
`https://api.thewatcher.io/survivor/set_bleeding_tokens/57ccc3018740d951a50eb448`
`{"user_id":"57b9e779421aa903403a7432","value":2}`

Log bleed shows up, survival doesn't
`https://api.thewatcher.io/settlement/get_event_log/57ccc3008740d951a50eb43c`
`{"survivor_id":"57ccc3018740d951a50eb448"}

**Comment by toconnell** [comment]
@CalebKester Oh! duh: I didn't realize you were doing it via _set_survial_. I was checking the wrong class method. Let me go check the right one and see how it looks.

**Comment by toconnell** [comment]
Ah, yup! As I initially suspected (in my first comment above), there's old style logging going on in that method and it doesn't get the event into the settlement's event log. 

Fixed in the next release:

```
@@ -1861,7 +1914,7 @@ class Survivor(Models.UserAsset):
         value = int(self.params["value"])
         self.survivor["survival"] = value
         self.apply_survival_limit()
-        self.logger.debug("%s set %s survival to %s" % (request.User, self, self.survivor["survival"]))
+        self.log_event("%s set %s survival to %s" % (request.User, self.pretty_name(), self.survivor["survival"]))
         self.save()
```

**Comment by CalebKester** [comment]
Yeah I didn't realize it either. Woops. Helps if you have the full story.
lol
