### ISSUE TITLE
/survivor/add_note/<survivor_id>	 does not return oid

### ISSUE THREAD

**Issue by CalebKester** [toconnell/kdm-manager#432]
According to the docs:
> Unlike other routes, this one returns the OID of the note:

However if you look at my postman call, all I get back is "OK!"

![image](https://user-images.githubusercontent.com/1319995/33471092-4bd3929e-d631-11e7-9b48-f91b1208fee6.png)

**Comment by toconnell** [comment]
@CalebKester Yeah, I just replicated this in test, but it's at odds w what's coded. Def a bug.

More soon...

**Comment by toconnell** [comment]
Oh snap! The return was missing.

Fixed:
```
@@ -2823,7 +2943,7 @@ class Survivor(Models.UserAsset):

         # notes
         elif action == 'add_note':
-            self.add_note()
+            return self.add_note()
         elif action == 'rm_note':
             self.rm_note()
```

This is going out in the next release.
