### ISSUE TITLE
set_many_attributes floods the event log

### ISSUE THREAD

**Issue by CalebKester** [toconnell/kdm-manager#434]
So using set_many_attributes right now basically renders the log useless. It creates a log for every attribute, not just the attributes that changed.

Here's what happens when I change the Luck to +1:

![image](https://user-images.githubusercontent.com/1319995/33520876-89d37ae8-d788-11e7-8be1-6b9801069496.png)

Can we get this changed to just log the attributes that changed?

**Comment by toconnell** [comment]
@CalebKester Yeah, that makes sense.

I'm going to try to finish up this release I've been working on all week and get it out today. I'll get a fix for this in there.

**Comment by toconnell** [comment]
Updated _set_attribute()_ method:

```
@@ -1438,6 +1491,11 @@ class Survivor(Models.UserAsset):
             self.logger.exception(msg)
             raise utils.InvalidUsage(msg, status_code=400)

+        #   necessity check - issue 434
+        if self.survivor[attrib] == value:
+            self.logger.debug("%s No change to '%s' attrib. Ignoring..." % (self, attrib))
+            return True
+
         self.survivor[attrib] = value
         self.log_event("%s set %s '%s' to %s" % (request.User.login, self.pretty_name(), attrib, value))
```

**Comment by toconnell** [comment]
Also added checkers to the wrapper:

```
@@ -1481,7 +1539,8 @@ class Survivor(Models.UserAsset):
             elif value is None:
                 raise utils.InvalidUsage(err_msg)

-            self.set_attribute(str(attrib), int(value), False)
+            if self.survivor[attrib] != value:
+                self.set_attribute(str(attrib), int(value), False)

         # do detail updates
         for u in detail_updates:
```

```
@@ -1493,7 +1552,8 @@ class Survivor(Models.UserAsset):
             for v in [attrib, detail, value]:
                 if v is None:
                     raise utils.InvalidUsage("The '%s' attribute of %s may not be undefined!" % (v, u))
-            self.set_attribute_detail(attrib, detail, value, False)
+            if self.survivor['attribute_detail'][attrib][detail] != value:
+                self.set_attribute_detail(attrib, detail, value, False)

         self.save()
```

**Comment by toconnell** [comment]
This should fix it. I basically updated the wrapper/harness method so that it doesn't call the actual update method unless the target value has to change. 

Also, just in case you're hitting the update method directly (e.g. via _set_attribute_), that has a necessity check as well before it fires.

Going out in the next release.
