### ISSUE TITLE
Quick Menu Image Clipping

### ISSUE THREAD

**Issue by WayForger** [toconnell/kdm-manager#440]
Hey TOC, 

The quick menu for accessing survivors is having issues with the background survivor image clipping through the Survival and Insanity values. It's been bugging me and I felt like I should bring to you're attention finally.

![screen shot 2017-12-07 at 6 11 08 pm](https://user-images.githubusercontent.com/30420007/33743344-693f0da6-db7a-11e7-9218-716e1237fd9c.png)

**Comment by toconnell** [comment]
@WayForger Thanks for letting me know!

Can you tell me what device and/or resolution is this happening at?

**Comment by WayForger** [comment]
I'm using the Manager on laptop but it happens on mobile as well.

**Comment by toconnell** [comment]
OK, @WayForger, I can dig it. For purposes of working on this, I'm going to ballpark it at 1100 x 600 and work it from that perspective. 

I'll have something for you in the next release (which I can hopefully do today) and I'll leave the ticket open so you can let me know how it works out.

More soon!

**Comment by toconnell** [comment]
Decided to cut the baby in half. Here's how we look at 1200x700 with a min-pixel-ratio of 1:

![1200x700](https://user-images.githubusercontent.com/48043/33805982-9c6d4c7a-dd86-11e7-896a-1621dcb3b187.PNG)

**Comment by toconnell** [comment]
Ok, I just took another run at this and...took a little more time with it. Here's what's going out in the next release:

![laptop_take_two](https://user-images.githubusercontent.com/48043/33852666-0ce61b44-de81-11e7-8eeb-6b85466c1502.PNG)

**Comment by toconnell** [comment]
Hey @WayForger 

When you get a chance, log in on your affected device(s) and let me know what's good!

**Comment by WayForger** [comment]
Looking great now. Thanks TOC!

**Comment by toconnell** [comment]
@WayForger Excellent. I'm going to close this out. Thanks again!
