### ISSUE TITLE
Timeline: End LY / Previous LY buttons missing

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#483]
From email:

> the lantern year is not automatically increased after a hunt/showdown. And I don't see anyway to increase it otherwise. 
----
Looks like we need a UI/UX tweak to optimize workflow here:
- [x] Add additional controls to the _next_ Lantern Year's modal overlay, e.g. `Start LY {{current_ly + 1}}`
- [x] Do the same thing for the previous LY's controls, e.g. `Return to {{current_ly -1}}` type of thing
- [x] If the checkbox for the _next_ LY is clicked, make that the current LY (just update $scope and do a `set_current_lantern_year` or something).

**Comment by toconnell** [comment]
I cloned the user, but I cannot reproduce this at present. Supposedly he's got a screen cap...

(Could be a JS evaluation bug, e.g. something to do with typing in the comparison/ng-if section.)

**Comment by gtsoul** [comment]
Hi,
please find the screenshots :
[Timeline](https://preview.ibb.co/kL5yA7/timeline.png)
[LY1](https://image.ibb.co/fZp3cn/inside_ly1.png)

**Comment by toconnell** [comment]
@gtsoul Thanks for uploading the screen captures! Can you click on LY0 and attach a screen capture of that as well?

**Comment by gtsoul** [comment]
Here it is : 
[Year 0](https://image.ibb.co/jQm8cn/inside_ly0.png)

Funny thing, the "end year N" label appeared when I zoomed out. 
Wouldn't be nice to add a "start year N+1" ,with the same effect on the next year ?

**Comment by toconnell** [comment]
@gtsoul Yes! That's a good idea: i'll work on that for the next release.

Also, I think there might be other ways that the new user interface for the Timeline could be improved.

Do you think it would help to have the "current" Lantern Year highlighted (or in bold case or something) to help draw the eye to it?

Also, do you think the control buttons for starting or ending a Lantern Year stand out enough? Do you think they need to be more obvious? 

Thanks!

**Comment by gtsoul** [comment]
In terms of UI improvement, I think that one of the way is to mimic the paper version (as the user is already used to that). 
On paper, when I finish a lantern year, I blacken the checkbox in front of it. So on KDM Manager, the current year is already obvious : it is the latest blackened year. But then, when I expect to check the next checkbox, it opens the year edition page.
It is a bit confusing, I was expecting more a thing like this : 
- click on the year label => year edition
- click on the year checkbox => advance to this year

Thank you for your responses

**Comment by toconnell** [comment]
OK @gtsoul ! Thanks again for your help!

I just updated the first comment on this ticket with a list of items I am going to work on for the next release. The changes should be in production before the end of the week!

**Comment by toconnell** [comment]
I just handled the boxes piece. It's looking pretty good:

![timeline_set_ly_w_checkboxes](https://user-images.githubusercontent.com/48043/37347122-1ee975dc-269f-11e8-9713-0d170da28695.gif)


CC: @gtsoul

**Comment by gtsoul** [comment]
Very nice

**Comment by toconnell** [comment]
This is done/dusted. I'm shipping it in the next break/fix release.
