### ISSUE TITLE
Settlement Bonus Missing - Dark Water Research

### ISSUE THREAD

**Issue by WayForger** [toconnell/kdm-manager#507]
Dark Water Research incorporates the following settlement bonus to a campaign: "Departing survivors gain +2 insanity." It is not included under the Settlement Bonuses area in the Manager and should be added. 
![screen shot 2018-07-27 at 7 02 49 pm](https://user-images.githubusercontent.com/30420007/43349740-e45f31b2-91cf-11e8-8e95-e528c8ef218e.png)
![screen shot 2018-07-27 at 7 03 22 pm](https://user-images.githubusercontent.com/30420007/43349742-e5fa2072-91cf-11e8-965c-91f870223b47.png)

**Comment by toconnell** [comment]
@WayForger Good catch! Must've missed that back when I keyed in the expansion assets. It's fixed in the next release:

```
diff --git a/v2/api/assets/innovations.py b/v2/api/assets/innovations.py
index 47ff928..031c8aa 100644
--- a/v2/api/assets/innovations.py
+++ b/v2/api/assets/innovations.py
@@ -552,6 +552,7 @@ expansion = {
         "expansion": "slenderman",
         "levels": 3,
         "endeavors": ['dark_water_research_0', 'dark_water_research_1'],
+        "departure_buff": "Departing survivors gain +2 insanity.",
     },
```
