### ISSUE TITLE
Missing Settlement Bonuses: Ultimate Weapon and Final Fighting Art

### ISSUE THREAD

**Issue by WayForger** [toconnell/kdm-manager#510]
I noticed this afternoon that the bonus offered by the Ultimate Weapon innovation was not among my Settlement Bonuses on the Manager. I've included screenshots below of my current innovation list and settlement bonuses showing the issue for Ultimate Weapon. I've included the Final Fighting Art as well as it does not show up either. 

![screen shot 2018-08-19 at 8 22 52 pm](https://user-images.githubusercontent.com/30420007/44315036-239f8180-a3ee-11e8-9dbd-47cfff02602d.png)

![screen shot 2018-08-19 at 8 26 04 pm](https://user-images.githubusercontent.com/30420007/44315035-2306eb00-a3ee-11e8-9907-91f0898f230f.png)

The Ultimate Weapon card text is: "When you defeat a monster, gain 1 monster resource of your choice from its resource deck."

The Final Fighting Art card text is: "Once per showdown, you may select a card from the discard pile or wound stack and place it on top of the AI deck. 

They both still add +1 to the Survival limit.

**Comment by toconnell** [comment]
Yeah @WayForger, good catch: I think I must've keyed this in back in like, 2015, and never got around to expanding them when I started tracking bonus/flavor text.

**Comment by toconnell** [comment]
This is fixed. Fix goes out in the next release of the API.
