### ISSUE TITLE
Campaign data lost

### ISSUE THREAD

**Issue by ingoclaro** [toconnell/kdm-manager#514]
I noticed that the campaign data is lost. Seems that if you aren't a subscriber the data is deleted automatically after 6 months.

It has been a while since I last used the app, so I missed the announcement about the data deletion.
If I subscribe now, would the data show up again (be recovered, is it just disabled?) Or indeed it was deleted and can't be recovered?

**Comment by toconnell** [comment]
Hello!

Sorry to hear about the trouble.

Depending on how long ago the settlement was removed, it may be recoverable. 

When non-subscribers log into the webapp, the settlements they have created are checked and if they are more than 180 days old, they are removed: if you have only just recently logged in, the settlement would only have been removed recently.

At any rate, if you want to give me the email address that created the settlement, I can check it out (if you are uncomfortable posting your email here, go ahead and use the tool in the webapp to report an error or problem, which emails me directly).

Thanks for using the Manager!

**Comment by toconnell** [comment]
@ingoclaro Oh, also, if you have more than one settlement you want me to check for, make sure to give me all the names (if you remember them).

Thanks again!

**Comment by ingoclaro** [comment]
Thanks for restoring the data!
