### ISSUE TITLE
Enhancement: Copies of Cards

### ISSUE THREAD

**Issue by superpowered** [toconnell/kdm-manager#522]
I may put in a PR to add this when I have the time to count them and make it, but I thought I'd just post the issue first.

It would be really useful, specifically on the resources (and possibly the gear) to have a count for how many copies the game ships with, as this affects the chances of drawing a specific card from a shuffled deck.

```
"_question_marks": {
    "selector_text": "???",
    "handle": "_question_marks",
    "name": "???",
    "rules": [
      
    ],
    "type_pretty": "Resources",
    "keywords": [
      "organ",
      "hide",
      "bone",
      "consumable"
    ],
    "sub_type_pretty": "Basic Resources",
    "type": "resources",
    "sub_type": "basic_resources",
    "desc": "You have no idea what monster bit this is. Can be used as a bone, organ, or hide!",
    "copies": 2
  }
```

**Comment by toconnell** [comment]
Handling this on https://github.com/toconnell/kdm-manager/pull/523

Closing this one out.
