### ISSUE TITLE
Account Authentication Issue: Log-In & Password Reset Failure

### ISSUE THREAD

**Issue by WayForger** [toconnell/kdm-manager#545]
Hey! I've had a lot more time to play KD as of recent event and wanted to utilize the Manager again. However, I currently unable able log-in or reset my password. 

While I am trying to log-in I am presented with the following: 
![Screen Shot 2020-04-23 at 7 57 54 PM](https://user-images.githubusercontent.com/30420007/80161078-3e4fd380-859d-11ea-9524-dd49647def7f.png)

While I try to reset my password I receive the following:
![Screen Shot 2020-04-23 at 8 01 02 PM](https://user-images.githubusercontent.com/30420007/80161147-69d2be00-859d-11ea-8bbc-889bb922b56d.png)

I love the Manager and would really like to be able to use it to support my campaign play soon. Hope you're well.

**Comment by toconnell** [comment]
Hey @WayForger !

So, two things.

First, I am almost done with a major, major overhaul of the Manager. I've been working on it for like...six months and wanted to have it out in March, but then, you know, COVID-19 and whatnot, but I plan to get it released in May (hopefully early).

The new releases fixes a tone of stuff, including this issue, which effects older subscribers when they try to reset their passwords. 

So, second, I'm going to go in and manually make a quick change to your user info and, after I'm done, you should be able to sign in again. I'll send you a quick all-clear when it's done. If I have to reset your password myself, I'll shoot you a DM with a temporary pw.

More soon!

**Comment by toconnell** [comment]
alright @WayForger give it another try whenever you get a chance: let me know how it goes.

**Comment by WayForger** [comment]
@toconnell everything is working great! Thank you so much for your time. I'm looking forward to all of the updates and additions in the latest release.
